import { Link } from "react-router-dom";
import { ArrowRight, Check, Cross, HandHeart, ShieldCheck, Users } from "lucide-react";
import Seo from "../components/Seo";
import { Reveal } from "../components/Reveal";
import { IMAGES, ORG, VALUES } from "../lib/content";

const convictions=[
  {icon:Cross,title:"A young person is created on purpose",body:"Identity cannot be built only around mistakes, hardship, family circumstances, school struggles, or what somebody else has said. We point young people toward the truth of who they are in Christ."},
  {icon:Users,title:"Relationships create room for growth",body:"Advice matters more after trust exists. Consistency, listening, honesty, accountability, and showing up over time are at the center of how we mentor."},
  {icon:HandHeart,title:"Practical help belongs beside prayer",body:"Faith is not separated from education, money, work, health, relationships, character, and opportunity. We want spiritual truth to become practical direction."},
];

export default function About(){return <>
  <Seo title="About" description={ORG.mission}/>

  <section className="pt-24 md:pt-28 bg-white overflow-hidden"><div className="max-w-7xl mx-auto px-6 md:px-12 py-12 sm:py-16 md:py-24 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
    <Reveal><div><p className="text-xs uppercase tracking-[.28em] text-[#A66F00] font-bold">About Consecrated Hands</p><h1 className="mt-5 font-heading text-[2.65rem] sm:text-5xl md:text-7xl lg:text-[5.2rem] font-semibold text-[#25292C]">Built to reach young people <span className="italic text-[#007BC2]">before crisis defines them.</span></h1><p className="mt-7 max-w-3xl text-xl text-[#424B52] leading-relaxed">Consecrated Hands exists to help young people discover who God created them to become and give them the relationships, guidance, skills, opportunities, and spiritual foundation to move toward that purpose.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/mission" className="inline-flex items-center gap-2 rounded-full bg-[#6FD3FF] text-[#25292C] px-7 py-3.5 font-extrabold">Our Mission <ArrowRight size={17}/></Link><Link to="/mentorship" className="inline-flex items-center gap-2 rounded-full border border-[#D8EEF8] px-7 py-3.5 font-bold text-[#25292C]">How We Mentor <ArrowRight size={17}/></Link></div></div></Reveal>
    <Reveal delay={.08}><img src={IMAGES.kidsSun} alt="Young people together in community" className="w-full aspect-[4/4.6] object-cover rounded-[2.25rem] shadow-[0_28px_70px_rgba(35,105,145,.14)]"/></Reveal>
  </div></section>

  <section className="py-16 sm:py-20 md:py-32 bg-[#F4FBFF]"><div className="max-w-7xl mx-auto px-6 md:px-12">
    <Reveal><div className="grid lg:grid-cols-[.75fr_1.25fr] gap-12"><div><p className="text-xs uppercase tracking-[.28em] text-[#A66F00] font-bold">The Conviction Behind the Work</p><h2 className="mt-4 font-heading text-4xl md:text-6xl font-semibold text-[#25292C]">A different future can begin with one faithful relationship.</h2></div><div className="lg:pt-5"><p className="text-xl leading-relaxed text-[#424B52]">Young people often receive attention after something has already gone wrong. Consecrated Hands is built around a different idea: reach them earlier, stay connected, and strengthen the parts of life that help purpose become possible.</p><p className="mt-6 text-lg leading-relaxed text-[#59636A]">We are not trying to replace parents, churches, schools, counselors, employers, or community organizations. We want to become another trustworthy strand around a young person—and help connect those strands when appropriate.</p></div></div></Reveal>
    <div className="mt-14 grid md:grid-cols-3 gap-5">{convictions.map(({icon:Icon,title,body},i)=><Reveal key={title} delay={i*.05}><div className="h-full bg-white rounded-3xl border border-[#D8EEF8] p-8"><div className="w-12 h-12 rounded-2xl bg-[#EAF9FF] flex items-center justify-center"><Icon className="text-[#006DAA]"/></div><h3 className="mt-5 font-heading text-3xl font-semibold text-[#25292C]">{title}</h3><p className="mt-4 text-[#59636A] leading-relaxed">{body}</p></div></Reveal>)}</div>
  </div></section>

  <section className="py-16 sm:py-20 md:py-32 bg-white"><div className="max-w-7xl mx-auto px-6 md:px-12 grid lg:grid-cols-[.8fr_1.2fr] gap-12">
    <Reveal><div><p className="text-xs uppercase tracking-[.28em] text-[#A66F00] font-bold">Our Foundation</p><h2 className="mt-4 font-heading text-[2.6rem] sm:text-5xl md:text-6xl font-semibold text-[#25292C]">Christ at the center. Relationships at the heart.</h2><p className="mt-6 text-lg text-[#59636A] leading-relaxed">These values shape how Consecrated Hands approaches mentorship, service, stewardship, partnership, and the responsibility of working around young people.</p></div></Reveal>
    <div className="grid md:grid-cols-2 gap-5">{VALUES.map((v,i)=><Reveal key={v.n} delay={(i%2)*.04}><div className="h-full bg-[#F4FBFF] rounded-3xl border border-[#D8EEF8] p-7"><div className="w-10 h-10 rounded-full bg-[#EAF9FF] text-[#006DAA] flex items-center justify-center"><Check size={18}/></div><h3 className="mt-4 font-heading text-3xl font-semibold text-[#25292C]">{v.title}</h3><p className="mt-3 text-[#59636A] leading-relaxed">{v.body}</p></div></Reveal>)}</div>
  </div></section>

  <section className="py-16 sm:py-20 md:py-24 bg-[#25292C] text-white"><div className="max-w-7xl mx-auto px-6 md:px-12 grid lg:grid-cols-2 gap-10 items-center">
    <Reveal><div><p className="text-xs uppercase tracking-[.28em] text-[#FFE066] font-bold">Public Charity & Stewardship</p><h2 className="mt-4 font-heading text-[2.6rem] sm:text-5xl md:text-6xl font-semibold">Faithful stewardship matters.</h2><p className="mt-6 text-lg text-white/80 leading-relaxed">Consecrated Hands is a federally recognized 501(c)(3) public charity. We believe Christian conviction and professional accountability belong together—clear programs, responsible stewardship, safe practices, and transparent communication.</p><p className="mt-5 text-white/80">EIN: <strong className="text-white">{ORG.ein}</strong></p></div></Reveal>
    <Reveal delay={.05}><div className="grid sm:grid-cols-2 gap-4"><Link to="/safeguarding" className="rounded-3xl border border-white/15 bg-white/[.07] p-6 hover:bg-white/[.1] transition"><ShieldCheck className="text-[#B8ECFF]"/><h3 className="mt-4 font-heading text-3xl">Youth Safeguarding</h3><p className="mt-2 text-white/75">Read our public commitment to safe, responsible youth-centered work.</p></Link><Link to="/privacy" className="rounded-3xl border border-white/15 bg-white/[.07] p-6 hover:bg-white/[.1] transition"><HandHeart className="text-[#FFE066]"/><h3 className="mt-4 font-heading text-3xl">Privacy</h3><p className="mt-2 text-white/75">See how website submissions and personal information are handled.</p></Link></div></Reveal>
  </div></section>

  <section className="py-16 sm:py-20 md:py-32 bg-[#F4FBFF]"><div className="max-w-5xl mx-auto px-6 text-center"><Reveal><p className="text-xs uppercase tracking-[.28em] text-[#A66F00] font-bold">The Work Ahead</p><h2 className="mt-4 font-heading text-[2.65rem] sm:text-5xl md:text-7xl font-semibold text-[#25292C]">Build a web strong enough to hold a future.</h2><p className="mt-6 text-lg text-[#59636A] leading-relaxed max-w-3xl mx-auto">Consecrated Hands is building a network of mentors, volunteers, churches, schools, businesses, donors, and community partners around young people who need consistent guidance and opportunity.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link to="/volunteer" className="inline-flex items-center gap-2 rounded-full bg-[#6FD3FF] text-[#25292C] px-7 py-3.5 font-extrabold">Get Involved <ArrowRight size={17}/></Link><Link to="/donate" className="inline-flex items-center gap-2 rounded-full bg-white border border-[#D8EEF8] text-[#25292C] px-7 py-3.5 font-bold">Support the Mission <ArrowRight size={17}/></Link></div></Reveal></div></section>
</>}
