import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import Marquee from "react-fast-marquee";
import { ArrowRight, ArrowUpRight, HandHeart } from "lucide-react";
import Seo from "../components/Seo";
import { Reveal } from "../components/Reveal";
import { ORG, PILLARS, MANIFESTO } from "../lib/content";

function Hero(){return <section className="relative overflow-hidden light-glow"><div className="max-w-7xl mx-auto px-6 md:px-12 pt-40 md:pt-48 pb-24"><div className="grid lg:grid-cols-2 gap-10 items-center"><div><motion.p initial={{opacity:0}} animate={{opacity:1}} className="text-xs md:text-sm uppercase tracking-[.3em] text-sky flex items-center gap-3"><span className="w-12 h-px bg-gold"/>Christ-centered youth mentorship</motion.p><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.15}} className="mt-8 font-heading text-5xl md:text-7xl lg:text-8xl font-semibold tracking-tight text-ink text-balance">Become Who God Set You Apart to <span className="italic text-gold">Be.</span></motion.h1><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.3}} className="mt-7 text-lg md:text-xl text-stone leading-relaxed max-w-xl">Relationship-first, Christ-centered mentorship connecting faith, stability, education, life skills, opportunity, character, and service — so young people can discover purpose and build a future.</motion.p><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.45}} className="mt-9 flex flex-wrap gap-4"><Link to="/mentorship" className="bg-sky text-white px-8 py-4 rounded-full font-semibold shadow-lg hover:-translate-y-1 transition">Explore Mentorship <ArrowRight className="inline ml-2" size={17}/></Link><Link to="/donate" className="bg-gold text-white px-8 py-4 rounded-full font-semibold">Support the Mission</Link></motion.div></div><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{delay:.2,duration:.8}} className="relative"><div className="absolute inset-10 rounded-full bg-sky/20 blur-3xl"/><img src={ORG.logo} alt="Consecrated Hands — Be Who God Set You Apart to Be" className="relative w-full max-w-2xl mx-auto object-contain"/></motion.div></div></div></section>}

function Purpose(){return <section className="py-24 md:py-36 bg-white"><div className="max-w-7xl mx-auto px-6 md:px-12 grid lg:grid-cols-12 gap-10"><div className="lg:col-span-3"><Reveal><p className="text-xs uppercase tracking-[.3em] text-gold">Why We Exist</p></Reveal></div><div className="lg:col-span-9"><Reveal><h2 className="font-heading text-4xl md:text-6xl font-semibold text-ink text-balance">Don't wait until someone is broken to try to rebuild them. <span className="italic text-sky">Reach them while they're young.</span></h2><p className="mt-8 text-lg text-stone leading-relaxed max-w-3xl">Consecrated Hands helps young people discover who God created them to become. We meet real needs without reducing a child to their problems, and we build the relationships, skills, confidence, faith, and opportunities that make a stronger future possible.</p><Link to="/about" className="inline-flex items-center gap-2 mt-8 font-semibold text-ink hover:text-sky">Our story <ArrowUpRight size={18}/></Link></Reveal></div></div></section>}

function Web(){return <section className="py-24 md:py-32 bg-sky-soft border-y border-line"><div className="max-w-7xl mx-auto px-6 md:px-12"><Reveal><p className="text-xs uppercase tracking-[.3em] text-gold mb-4">Our Mentorship Framework</p><h2 className="font-heading text-5xl md:text-7xl font-semibold text-ink">The Web of Consecration™</h2><p className="mt-5 text-lg text-stone max-w-3xl">One strand alone isn't the web. Each area of a young person's life connects to the others, and every healthy connection makes the whole structure stronger.</p></Reveal><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5 mt-14">{PILLARS.map((p,i)=><Reveal key={p.n} delay={(i%4)*.05}><Link to="/mentorship" className="block h-full bg-white rounded-3xl p-7 border border-line shadow-sm hover:-translate-y-1 hover:shadow-lg transition"><span className="text-sm font-bold text-gold">{p.n}</span><h3 className="font-heading text-3xl font-semibold mt-3 text-ink">{p.title}</h3><p className="mt-3 text-stone leading-relaxed text-sm">{p.desc}</p></Link></Reveal>)}</div></div></section>}

function Journey(){return <section className="py-24 md:py-36 bg-white"><div className="max-w-6xl mx-auto px-6 md:px-12 text-center"><Reveal><p className="text-xs uppercase tracking-[.3em] text-gold">The Goal</p><h2 className="mt-5 font-heading text-5xl md:text-7xl font-semibold text-ink">From “Help me” to <span className="italic text-sky">“Now I can help somebody else.”</span></h2><p className="mt-7 text-lg text-stone max-w-3xl mx-auto leading-relaxed">Mentorship should create momentum. A young person who receives stability, guidance, education, opportunity, and spiritual support can grow into a leader who strengthens the next person.</p></Reveal></div></section>}

function FinalCTA(){return <section className="py-24 md:py-36 light-glow"><div className="max-w-5xl mx-auto px-6 text-center"><Reveal><HandHeart size={44} className="text-gold mx-auto mb-7"/><h2 className="font-heading text-5xl md:text-7xl font-semibold text-ink">Help build the next strand.</h2><p className="mt-6 text-lg text-stone max-w-2xl mx-auto">Give, mentor, volunteer, partner, or pray. Every faithful connection can become part of a young person's future.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link to="/donate" className="bg-gold text-white px-8 py-4 rounded-full font-semibold">Give Today</Link><Link to="/volunteer" className="bg-sky text-white px-8 py-4 rounded-full font-semibold">Volunteer or Mentor</Link><Link to="/prayer" className="bg-white border border-line text-ink px-8 py-4 rounded-full font-semibold">Request Prayer</Link></div></Reveal></div></section>}

export default function Home(){return <><Seo title="Home" description={ORG.mission}/><Hero/><Purpose/><Web/><Journey/><section className="py-12 bg-sky overflow-hidden"><Marquee speed={38} gradient={false} autoFill>{MANIFESTO.map((m,i)=><span key={i} className="marquee-item text-white text-4xl md:text-6xl mx-8">{m} <span className="text-gold-soft ml-8">✦</span></span>)}</Marquee></section><FinalCTA/></>}
