import { Link } from "react-router-dom";
import { ArrowRight, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import Seo from "../components/Seo";
import { Reveal } from "../components/Reveal";
import { ORG, PILLARS } from "../lib/content";

const Button=({to,children,light=false})=><Link to={to} className={`${light?"bg-white text-[#17364B] border border-[#C9D9E2]":"bg-[#73C8FF] text-[#17364B]"} inline-flex items-center gap-2 px-7 py-3.5 rounded-full font-extrabold shadow-sm hover:-translate-y-0.5 transition`}>{children}<ArrowRight size={17}/></Link>;

function Hero(){return <section className="relative overflow-hidden bg-white pt-36 md:pt-44 pb-20 md:pb-28"><div className="absolute -top-24 -right-24 w-[34rem] h-[34rem] rounded-full bg-[#EAF7FF] blur-3xl opacity-80"/><div className="absolute top-28 left-[-10rem] w-[28rem] h-[28rem] rounded-full bg-[#FFF6D9] blur-3xl opacity-55"/><div className="relative max-w-7xl mx-auto px-6 md:px-12 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center"><div><Reveal><div className="inline-flex items-center gap-2 rounded-full bg-[#F4FBFF] border border-[#DCEFFA] px-4 py-2 text-xs font-bold tracking-[.18em] uppercase text-[#405E70]"><Sparkles size={14} className="text-[#8A650C]"/>Christ-centered youth mentorship</div><h1 className="mt-7 font-heading text-[3.3rem] leading-[.98] md:text-7xl lg:text-[5.7rem] font-semibold tracking-tight text-[#17364B]">Become Who God Set You Apart to <span className="text-[#A77A10] italic">Be.</span></h1><p className="mt-7 max-w-2xl text-lg md:text-xl leading-relaxed text-[#526B7A]">Consecrated Hands walks with young people before crisis defines them — strengthening faith, stability, education, practical skills, opportunity, character, leadership, and service.</p><div className="mt-9 flex flex-wrap gap-3"><Button to="/mentorship">Explore Mentorship</Button><Button to="/donate" light>Support the Mission</Button></div></Reveal></div><Reveal delay={.12}><div className="relative"><div className="absolute inset-10 rounded-full bg-[#DFF3FF] blur-3xl"/><div className="relative rounded-[2.5rem] border border-[#DCE8EF] bg-white/90 shadow-[0_30px_80px_rgba(49,112,151,.14)] p-6 md:p-10"><img src={ORG.logo} alt="Consecrated Hands" className="w-full max-h-[34rem] object-contain"/></div></div></Reveal></div></section>}

function Intro(){return <section className="py-24 md:py-32 bg-[#F8FCFF]"><div className="max-w-6xl mx-auto px-6 md:px-12"><Reveal><div className="grid md:grid-cols-[.8fr_1.2fr] gap-10 md:gap-16"><div><p className="text-xs uppercase tracking-[.28em] text-[#8A650C] font-bold">Why We Exist</p><h2 className="mt-4 font-heading text-4xl md:text-6xl font-semibold text-[#17364B]">Reach them early. Walk with them fully.</h2></div><div className="md:pt-6"><p className="text-xl md:text-2xl leading-relaxed text-[#405E70]">We do not reduce a young person to what is going wrong in their life. We help them discover who God created them to be and strengthen the connected areas that help purpose become possible.</p><p className="mt-6 text-base md:text-lg leading-relaxed text-[#526B7A]">That means trusted relationships, practical support, spiritual formation, education, life skills, opportunity, healthy character, leadership, and a path toward giving back.</p></div></div></Reveal></div></section>}

function Web(){return <section className="py-24 md:py-32 bg-white"><div className="max-w-7xl mx-auto px-6 md:px-12"><Reveal><div className="max-w-3xl"><p className="text-xs uppercase tracking-[.28em] text-[#8A650C] font-bold">Our Mentorship Framework</p><h2 className="mt-4 font-heading text-5xl md:text-7xl font-semibold text-[#17364B]">The Web of Consecration™</h2><p className="mt-5 text-lg leading-relaxed text-[#526B7A]">Every strand matters. When one area gets stronger, it can strengthen the others too.</p></div></Reveal><div className="mt-12 grid md:grid-cols-2 lg:grid-cols-3 gap-5">{PILLARS.map((p,i)=><Reveal key={p.n} delay={(i%3)*.05}><article className="h-full rounded-[1.75rem] border border-[#DCE8EF] bg-white p-7 md:p-8 shadow-[0_12px_35px_rgba(44,94,126,.06)] hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(44,94,126,.10)] transition"><div className="w-11 h-11 rounded-full bg-[#EAF7FF] flex items-center justify-center text-[#176F9F] font-bold text-sm">{p.n}</div><h3 className="mt-5 font-heading text-3xl font-semibold text-[#17364B]">{p.title}</h3><p className="mt-3 text-[#526B7A] leading-relaxed">{p.desc}</p></article></Reveal>)}</div><Reveal><div className="mt-10"><Button to="/mentorship">See the Full Framework</Button></div></Reveal></div></section>}

function Difference(){return <section className="py-24 md:py-32 bg-[#16384F] text-white"><div className="max-w-7xl mx-auto px-6 md:px-12"><Reveal><div className="max-w-3xl"><p className="text-xs uppercase tracking-[.28em] text-[#F5D875] font-bold">What Makes This Different</p><h2 className="mt-4 font-heading text-5xl md:text-7xl font-semibold">Relationship first. Purpose always.</h2></div></Reveal><div className="mt-12 grid md:grid-cols-3 gap-5"><Reveal><div className="rounded-3xl bg-white/[0.07] border border-white/15 p-7"><HeartHandshake className="text-[#9AD8FF]"/><h3 className="mt-5 font-heading text-3xl">Consistency</h3><p className="mt-3 text-white/80 leading-relaxed">Young people need adults who show up, listen, and stay present long enough for trust to become real.</p></div></Reveal><Reveal delay={.06}><div className="rounded-3xl bg-white/[0.07] border border-white/15 p-7"><ShieldCheck className="text-[#9AD8FF]"/><h3 className="mt-5 font-heading text-3xl">Whole-Life Support</h3><p className="mt-3 text-white/80 leading-relaxed">Faith and practical life are not separated. We mentor the whole young person, not one isolated problem.</p></div></Reveal><Reveal delay={.12}><div className="rounded-3xl bg-white/[0.07] border border-white/15 p-7"><Sparkles className="text-[#F5D875]"/><h3 className="mt-5 font-heading text-3xl">A Future Beyond Survival</h3><p className="mt-3 text-white/80 leading-relaxed">The goal is growth from “help me” into leadership, service, purpose, and eventually helping someone else.</p></div></Reveal></div></div></section>}

function CTA(){return <section className="py-24 md:py-32 bg-[#F8FCFF]"><div className="max-w-5xl mx-auto px-6 text-center"><Reveal><p className="text-xs uppercase tracking-[.28em] text-[#8A650C] font-bold">Build the Next Strand</p><h2 className="mt-4 font-heading text-5xl md:text-7xl font-semibold text-[#17364B]">Give. Mentor. Volunteer. Pray.</h2><p className="mt-6 max-w-2xl mx-auto text-lg text-[#526B7A] leading-relaxed">Every faithful connection can become part of a young person’s future.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Button to="/donate">Give Today</Button><Button to="/volunteer" light>Volunteer or Mentor</Button><Button to="/prayer" light>Request Prayer</Button></div></Reveal></div></section>}

export default function Home(){return <><Seo title="Home" description={ORG.mission}/><Hero/><Intro/><Web/><Difference/><CTA/></>}
