import { Link } from "react-router-dom";
import { ArrowRight, Compass, Cross, Users } from "lucide-react";
import Seo from "../components/Seo";
import { Reveal } from "../components/Reveal";
import { ORG } from "../lib/content";

const cards=[
  {icon:Cross,title:"Faith that gives identity",body:"Young people need to know they are created intentionally, loved by God, and called toward a life with purpose."},
  {icon:Users,title:"Relationships that create stability",body:"Consistent mentors, healthy community, trusted adults, and a sense of belonging create the conditions for growth."},
  {icon:Compass,title:"Skills and opportunity that create direction",body:"Education, life skills, financial understanding, career exposure, and leadership help purpose become practical."}
];

export default function Mission(){return <><Seo title="Our Mission" description={ORG.mission}/><section className="pt-40 pb-24 bg-white"><div className="max-w-6xl mx-auto px-6 md:px-12"><Reveal><p className="text-xs uppercase tracking-[.28em] text-[#D6A62A] font-bold">Our Mission</p><h1 className="mt-5 font-heading text-5xl md:text-7xl lg:text-8xl font-semibold text-[#17364B] max-w-5xl">Reach them early. Walk with them fully. Point them toward <span className="italic text-[#63BDF3]">purpose in Christ.</span></h1></Reveal></div></section><section className="py-20 bg-[#F8FCFF]"><div className="max-w-6xl mx-auto px-6 md:px-12"><Reveal><p className="text-xl md:text-3xl leading-relaxed text-[#496777] max-w-5xl">{ORG.mission}</p></Reveal><div className="grid md:grid-cols-3 gap-5 mt-12">{cards.map(({icon:Icon,title,body},i)=><Reveal key={title} delay={i*.05}><div className="h-full rounded-3xl bg-white border border-[#E4EEF4] p-8"><div className="w-12 h-12 rounded-2xl bg-[#EAF7FF] flex items-center justify-center"><Icon className="text-[#3A9FD9]"/></div><h2 className="mt-5 font-heading text-3xl font-semibold text-[#17364B]">{title}</h2><p className="mt-4 text-[#6A7F8D] leading-relaxed">{body}</p></div></Reveal>)}</div></div></section><section className="py-24 bg-white"><div className="max-w-5xl mx-auto px-6 text-center"><Reveal><p className="text-xs uppercase tracking-[.28em] text-[#D6A62A] font-bold">The Long-Term Goal</p><h2 className="mt-4 font-heading text-5xl md:text-7xl font-semibold text-[#17364B]">From “help me” to <span className="italic text-[#63BDF3]">“now I can help somebody else.”</span></h2><p className="mt-6 text-lg text-[#667C8A] max-w-3xl mx-auto leading-relaxed">We want young people to grow into stable, capable, Christ-centered adults who lead, serve, give back, and strengthen the next person.</p><Link to="/mentorship" className="inline-flex mt-8 items-center gap-2 bg-[#73C8FF] text-white px-7 py-3.5 rounded-full font-bold">See The Web of Consecration™ <ArrowRight size={17}/></Link></Reveal></div></section></>}
