import { useState } from "react";
import axios from "axios";
import { toast } from "sonner";
import { Check, HandHeart, Loader2 } from "lucide-react";
import Seo from "../components/Seo";
import { Reveal } from "../components/Reveal";
import { ORG } from "../lib/content";

const API_BASE=(process.env.REACT_APP_BACKEND_URL||"").replace(/\/$/,"");
const API=API_BASE?`${API_BASE}/api`:"";
const input="w-full rounded-2xl border border-[#DDEBF3] bg-white px-4 py-3.5 text-[#17364B] placeholder:text-[#91A4B0] focus:outline-none focus:ring-2 focus:ring-[#73C8FF]/40 focus:border-[#73C8FF]";

export default function Prayer(){
  const [form,setForm]=useState({name:"",email:"",request:"",is_public:false});
  const [loading,setLoading]=useState(false);const [done,setDone]=useState(false);
  const update=k=>e=>setForm(f=>({...f,[k]:e.target.value}));
  const submit=async e=>{e.preventDefault();if(!form.request.trim()){toast.error("Please share your prayer request.");return;}if(!API){const subject="Prayer request submitted through ConsecratedHands.com";const body=[`Name: ${form.name||"Anonymous"}`,`Email: ${form.email||"Not provided"}`,`May be shared anonymously: ${form.is_public?"Yes":"No"}`,"",form.request].join("\n");toast.success("Your email app is opening so you can send the prayer request.");window.location.href=`mailto:${ORG.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;return;}setLoading(true);try{const {data}=await axios.post(`${API}/prayer`,form);toast.success(data.message||"Thank you — our team will be praying for you.");setDone(true);setForm({name:"",email:"",request:"",is_public:false});}catch{toast.error("Something went wrong. Please try again.");}finally{setLoading(false)}};
  return <><Seo title="Prayer Requests" description="Share a prayer request with Consecrated Hands."/><section className="pt-40 pb-20 bg-white"><div className="max-w-5xl mx-auto px-6 text-center"><Reveal><p className="text-xs uppercase tracking-[.28em] text-[#D6A62A] font-bold">Prayer Requests</p><h1 className="mt-5 font-heading text-5xl md:text-7xl font-semibold text-[#17364B]">Let us pray <span className="italic text-[#63BDF3]">with you.</span></h1><p className="mt-6 max-w-2xl mx-auto text-lg text-[#687E8D] leading-relaxed">Whatever you are carrying, you do not have to carry it alone. Share your request and our team will lift it up in prayer.</p></Reveal></div></section><section className="pb-24 bg-[#F8FCFF]"><div className="max-w-2xl mx-auto px-6 -mt-4"><Reveal><div className="rounded-[2rem] bg-white border border-[#E2EDF4] shadow-[0_20px_60px_rgba(41,91,123,.08)] p-7 md:p-10">{done?<div className="text-center py-8"><div className="w-16 h-16 rounded-full bg-[#EAF7FF] flex items-center justify-center mx-auto"><Check className="text-[#3A9FD9]" size={30}/></div><h2 className="mt-5 font-heading text-4xl font-semibold text-[#17364B]">Your request has been received.</h2><p className="mt-3 text-[#6A7F8D]">Our team is honored to pray with you.</p><button onClick={()=>setDone(false)} className="mt-6 text-[#3A9FD9] font-bold">Submit another request</button></div>:<form onSubmit={submit} className="space-y-6"><div className="grid md:grid-cols-2 gap-5"><label className="text-sm font-semibold text-[#536D7E]">Name <span className="font-normal text-[#93A4AF]">optional</span><input className={`${input} mt-2`} value={form.name} onChange={update("name")} placeholder="Your name"/></label><label className="text-sm font-semibold text-[#536D7E]">Email <span className="font-normal text-[#93A4AF]">optional</span><input type="email" className={`${input} mt-2`} value={form.email} onChange={update("email")} placeholder="you@email.com"/></label></div><label className="block text-sm font-semibold text-[#536D7E]">Your prayer request<textarea rows={6} className={`${input} mt-2 resize-none`} value={form.request} onChange={update("request")} placeholder="Share what is on your heart…"/></label><label className="flex gap-3 items-start text-sm text-[#6A7F8D]"><input type="checkbox" checked={form.is_public} onChange={e=>setForm(f=>({...f,is_public:e.target.checked}))} className="mt-1 accent-[#73C8FF]"/>You may share this request anonymously with our prayer team community.</label><button disabled={loading} className="w-full rounded-full bg-[#73C8FF] text-white py-4 font-bold flex items-center justify-center gap-2 hover:-translate-y-0.5 transition disabled:opacity-60">{loading?<><Loader2 className="animate-spin" size={18}/>Sending…</>:<><HandHeart size={18}/>Send Prayer Request</>}</button></form>}</div></Reveal></div></section></>
}
