import { Link } from "react-router-dom";
import { BookOpen, Briefcase, HandHeart, Users } from "lucide-react";
import Seo from "../components/Seo";
import { Reveal } from "../components/Reveal";

const roles=[
  {icon:HandHeart,title:"Mentor a young person",body:"Be a consistent, trustworthy adult who listens, encourages, prays, and walks with a young person over time."},
  {icon:BookOpen,title:"Support learning",body:"Help with tutoring, reading, study habits, GED preparation, confidence, and educational development."},
  {icon:Briefcase,title:"Open a door",body:"Share career knowledge, job-readiness support, workplace exposure, internships, or employment opportunities."},
  {icon:Users,title:"Serve at events",body:"Help create safe, positive experiences through sports, outings, meals, activities, outreach, and community events."}
];

export default function Volunteer(){return <><Seo title="Volunteer" description="Mentor, volunteer, or partner with Consecrated Hands."/><section className="pt-40 pb-20 bg-white"><div className="max-w-6xl mx-auto px-6 md:px-12"><Reveal><p className="text-xs uppercase tracking-[.28em] text-[#8A650C] font-bold">Get Involved</p><h1 className="mt-5 font-heading text-5xl md:text-7xl lg:text-8xl font-semibold text-[#17364B] max-w-5xl">Be the person who <span className="italic text-[#2F8FC7]">shows up.</span></h1><p className="mt-7 max-w-3xl text-xl text-[#526B7A] leading-relaxed">Young people remember consistency. Whether you mentor, tutor, share a career, serve at an event, partner as a church or business, or help behind the scenes, your presence can strengthen the web around a young life.</p></Reveal></div></section><section className="py-24 bg-[#F8FCFF]"><div className="max-w-7xl mx-auto px-6 md:px-12 grid md:grid-cols-2 gap-5">{roles.map(({icon:Icon,title,body},i)=><Reveal key={title} delay={(i%2)*.05}><div className="h-full bg-white rounded-3xl border border-[#DCE8EF] p-8"><div className="w-12 h-12 rounded-2xl bg-[#EAF7FF] flex items-center justify-center"><Icon className="text-[#176F9F]"/></div><h2 className="mt-5 font-heading text-3xl font-semibold text-[#17364B]">{title}</h2><p className="mt-3 text-[#526B7A] leading-relaxed">{body}</p></div></Reveal>)}</div></section><section className="py-24 bg-white"><div className="max-w-4xl mx-auto px-6 text-center"><Reveal><h2 className="font-heading text-5xl md:text-6xl font-semibold text-[#17364B]">Ready to serve?</h2><p className="mt-5 text-lg text-[#526B7A] leading-relaxed">Youth-facing volunteer and mentor placement may include screening, training, safeguarding expectations, and role matching. Contact us to begin the conversation.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/contact" className="inline-flex bg-[#73C8FF] text-[#17364B] px-7 py-3.5 rounded-full font-extrabold">Contact Consecrated Hands</Link><Link to="/safeguarding" className="inline-flex border border-[#C9D9E2] text-[#17364B] px-7 py-3.5 rounded-full font-bold">Read Youth Safeguarding</Link></div></Reveal></div></section></>}
